{"content": {"suites": {"0": {"status": {"total_pass": 12, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 9, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_faithfulness[Start up alignment values are incorrect (or very bad)]", "rerun": "0"}, "1": {"status": "FAIL", "message": "   AssertionError: Context precision score too low (0.6407009605397548) for input: Startup calibration alignment screen is empty.\n   assert 0.6407009605397548 > 0.7\n", "test_name": "test_faithfulness[Startup calibration alignment screen is empty.]", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_faithfulness[Streaks appear in the printed content.]", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_faithfulness[Troubleshooting Guide. Print Quality - Strike-through or mottling]", "rerun": "0"}, "4": {"status": "FAIL", "message": "   AssertionError: Context precision score too low (0.6148115773059881) for input: Supply fan not running\n   assert 0.6148115773059881 > 0.7\n", "test_name": "test_faithfulness[Supply fan not running]", "rerun": "0"}, "5": {"status": "FAIL", "message": "       pymysql.err.ProgrammingError: nan can not be used with MySQL\n       sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) nan can not be used with MySQL\n       [SQL: INSERT INTO ragas_evaluation (session_id, user_input, response, retrieved_contexts, faithfulness_score, context_precision_score, factual_correctness_score) VALUES (%(session_id)s, %(user_input)s, %(response)s, %(retrieved_contexts)s, %(faithfulness_score)s, %(context_precision_score)s, %(factual_correctness_score)s)]\n       [parameters: {'session_id': '448ec839-acf3-418d-8d6b-9a0a0c027f73', 'user_input': 'Gen2.5 Pen Pocket Board. System Status LED Guide', 'response': '', 'retrieved_contexts': None, 'faithfulness_score': nan, 'context_precision_score': 0.0, 'factual_correctness_score': None}]\n       (Background on this error at: https://sqlalche.me/e/20/f405)\n", "test_name": "test_faithfulness[Gen2.5 Pen Pocket Board. System Status LED Guide]", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_faithfulness[TOF (Top of Form) faults too early]", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_faithfulness[TOF sensor improperly positioned]", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_faithfulness[TOF sensor light beam not working]", "rerun": "0"}, "9": {"status": "FAIL", "message": "       pymysql.err.ProgrammingError: nan can not be used with MySQL\n       sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) nan can not be used with MySQL\n       [SQL: INSERT INTO ragas_evaluation (session_id, user_input, response, retrieved_contexts, faithfulness_score, context_precision_score, factual_correctness_score) VALUES (%(session_id)s, %(user_input)s, %(response)s, %(retrieved_contexts)s, %(faithfulness_score)s, %(context_precision_score)s, %(factual_correctness_score)s)]\n       [parameters: {'session_id': '448ec839-acf3-418d-8d6b-9a0a0c027f73', 'user_input': 'TOF was failing to recognize TOF mark during Arch to Arch Calibration', 'response': '', 'retrieved_contexts': None, 'faithfulness_score': nan, 'context_precision_score': 0.0, 'factual_correctness_score': None}]\n       (Background on this error at: https://sqlalche.me/e/20/f405)\n", "test_name": "test_faithfulness[TOF was failing to recognize TOF mark during Arch to Arch Calibration]", "rerun": "0"}, "10": {"status": "FAIL", "message": "   AssertionError: Context precision score too low (0.6676485551411369) for input: Temperature Control Problem\n   assert 0.6676485551411369 > 0.7\n", "test_name": "test_faithfulness[Temperature Control Problem]", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_faithfulness[Tensions across the press too low]", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_faithfulness[Tensions are unstable]", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_faithfulness[Text Doubling defects occurring in the middle of a print run.]", "rerun": "0"}, "14": {"status": "FAIL", "message": "       pymysql.err.ProgrammingError: nan can not be used with MySQL\n       sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) nan can not be used with MySQL\n       [SQL: INSERT INTO ragas_evaluation (session_id, user_input, response, retrieved_contexts, faithfulness_score, context_precision_score, factual_correctness_score) VALUES (%(session_id)s, %(user_input)s, %(response)s, %(retrieved_contexts)s, %(faithfulness_score)s, %(context_precision_score)s, %(factual_correctness_score)s)]\n       [parameters: {'session_id': '448ec839-acf3-418d-8d6b-9a0a0c027f73', 'user_input': 'The crossweb width of the printed content is smaller than expected.', 'response': '', 'retrieved_contexts': None, 'faithfulness_score': nan, 'context_precision_score': 0.0, 'factual_correctness_score': None}]\n       (Background on this error at: https://sqlalche.me/e/20/f405)\n", "test_name": "test_faithfulness[The crossweb width of the printed content is smaller than expected.]", "rerun": "0"}, "15": {"status": "FAIL", "message": "   AssertionError: Faithfulness score too low for input: The downweb length of the printed content is longer or shorter than expected.\n   assert 0.44680851063829785 > 0.7\n", "test_name": "test_faithfulness[The downweb length of the printed content is longer or shorter than expected.]", "rerun": "0"}, "16": {"status": "PASS", "message": "", "test_name": "test_faithfulness[The fonts in the printed content do not match the source file.]", "rerun": "0"}, "17": {"status": "PASS", "message": "", "test_name": "test_faithfulness[The media width calculated and reported by the Inline Process Controller does not closely match the actual media width.]", "rerun": "0"}, "18": {"status": "PASS", "message": "", "test_name": "test_faithfulness[Server LED status]", "rerun": "0"}, "19": {"status": "FAIL", "message": "       pymysql.err.ProgrammingError: nan can not be used with MySQL\n       sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) nan can not be used with MySQL\n       [SQL: INSERT INTO ragas_evaluation (session_id, user_input, response, retrieved_contexts, faithfulness_score, context_precision_score, factual_correctness_score) VALUES (%(session_id)s, %(user_input)s, %(response)s, %(retrieved_contexts)s, %(faithfulness_score)s, %(context_precision_score)s, %(factual_correctness_score)s)]\n       [parameters: {'session_id': '448ec839-acf3-418d-8d6b-9a0a0c027f73', 'user_input': 'The side 2 content is not aligned with the side 1 content in the downweb direction.', 'response': '', 'retrieved_contexts': None, 'faithfulness_score': nan, 'context_precision_score': 0.0, 'factual_correctness_score': None}]\n       (Background on this error at: https://sqlalche.me/e/20/f405)\n", "test_name": "test_faithfulness[The side 2 content is not aligned with the side 1 content in the downweb direction.]", "rerun": "0"}, "20": {"status": "FAIL", "message": "       pymysql.err.ProgrammingError: nan can not be used with MySQL\n       sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) nan can not be used with MySQL\n       [SQL: INSERT INTO ragas_evaluation (session_id, user_input, response, retrieved_contexts, faithfulness_score, context_precision_score, factual_correctness_score) VALUES (%(session_id)s, %(user_input)s, %(response)s, %(retrieved_contexts)s, %(faithfulness_score)s, %(context_precision_score)s, %(factual_correctness_score)s)]\n       [parameters: {'session_id': '448ec839-acf3-418d-8d6b-9a0a0c027f73', 'user_input': 'The size of the chipout region is different than expected.', 'response': '', 'retrieved_contexts': None, 'faithfulness_score': nan, 'context_precision_score': 0.0, 'factual_correctness_score': None}]\n       (Background on this error at: https://sqlalche.me/e/20/f405)\n", "test_name": "test_faithfulness[The size of the chipout region is different than expected.]", "rerun": "0"}}, "suite_name": "test3.py"}}}, "date": "April 16, 2025", "start_time": 1744790495.3081977, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "12", "fail": "9", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "21"}